version: '3.3'
services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE-ME
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - sssl_reg_network
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - DATABASE_URL= postgres://postgres:CHANGE-ME@db
    restart: always
    ports:
      - "3000:3000"
    networks:
      - sssl_reg_network
    depends_on:
      - db
networks:
  sssl_reg_network:
volumes:
  database_folder:
    external:
      name: sssl_reg_database
